kind: Service
apiVersion: v1
metadata:
  name: {{ template "playerbio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "playerbio.name" . }}
    chart: {{ template "playerbio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "playerbio.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
    name: http
