{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ template "playerbio.fullname" . }}
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    app: {{ template "playerbio.name" . }}
    chart: {{ template "playerbio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceMonitorSelector:
    matchLabels:
      app: {{ template "playerbio.name" . }}
      release: {{ .Release.Name }}
  podMonitorSelector:
    matchLabels:
      app: {{ template "playerbio.name" . }}
      release: {{ .Release.Name }}
  enableAdminAPI: false
  serviceAccountName: {{ .Values.prometheus.serviceAccount }}
{{- end }}
