# Default values for splunk enterprise.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Nginx configuration.
##
nginx:
  replicaCount: 1
  image:
    name: nginx
    tag: "1.17"
  service:
    type: ClusterIP
    port: 80

## Splunk web UI admin password.
##
password: helloworld

## Docker image properties.
##
image:
  name: splunk/splunk
  tag: "7.2"

## Indexer cluster properties.
##
indexer:
  replicaCount: 1
  service:
    type: ClusterIP
    splunkwebPort: 8000
    splunkdPort: 8089
    hecPort: 8088
    replicationPort: 4001
    s2sPort: 9997

## Master instance properties.
##
master:
  replicaCount: 1
  service:
    type: ClusterIP
    splunkwebPort: 8000
    splunkdPort: 8089

## Search instance properties.
##
search:
  replicaCount: 1
  service:
    type: ClusterIP
    splunkwebPort: 8000
    splunkdPort: 8089
    kvPort: 8191
