# grafana service setup to expose via minikube
grafana:
  service:
    type: NodePort

# service monitor selectors for kubernetes components in minikube
coreDns:
  service:
    selector:
      k8s-app: kube-dns

kubeControllerManager:
  service:
    selector:
      k8s-app: null
      component: kube-controller-manager

kubeEtcd:
  service:
    selector:
      k8s-app: null
      component: etcd

kubeScheduler:
  service:
    selector:
      k8s-app: null
      component: kube-scheduler
