---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "splunk.fullname" . }}-master
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "splunk.name" . }}-master
    chart: {{ template "splunk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.master.service.type }}
  {{- if eq .Values.master.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  selector:
    app: {{ template "splunk.name" . }}-master
    release: {{ .Release.Name }}
  ports:
    - name: splunkweb
      port: {{ .Values.master.service.splunkwebPort }} 
      targetPort: web
    - name: splunkd
      port: {{ .Values.master.service.splunkdPort }}
      targetPort: mgmt
