httpPort: 8080

replicaCount: 1

image:
  repository: playerbio
  tag: latest
  pullPolicy: IfNotPresent

# pod arguments
args: ["start"]

# pod environment variables
env: []
# - name: MIX_ENV
#   value: prod

resources: {}
# requests:
#   cpu: 10m
#   memory: 32Mi

# pod security context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  allowPrivEsc: false

podAnnotations: {}

podLabels: {}

service:
  type: NodePort
  port: 80

probes:
  enabled: true
  liveness:
    path: /ping
  readiness:
    path: /ping

prometheus:
  enabled: false
  namespace: default
  interval: 15s
  path: /metrics
  serviceAccount: default
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
