httpPort: 8080

replicaCount: 5

image:
  repository: playerbio
  tag: latest
  pullPolicy: Never

# Pod arguments
args: ["start"]

# Pod environment variables
env: []
# - name: MIX_ENV
#   value: prod

resources: {}
# requests:
#   cpu: 10m
#   memory: 32Mi

# Pod Security Context
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001
  allowPrivEsc: false

podAnnotations: {}

podLabels: {}

service:
  type: NodePort
  port: 60000

probes:
  enabled: true
  liveness:
    path: /ping
  readiness:
    path: /ping
