apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk.fullname" . }}-nginx
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "splunk.name" . }}
    chart: {{ template "splunk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx-static.conf: |-
    server {
      listen 80;

      location / {
        root /data/www;
        autoindex on;
      }
    }
