---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "splunk.fullname" . }}-defaults
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "splunk.name" . }}-defaults
    chart: {{ template "splunk.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.nginx.service.type }}
  {{- if eq .Values.nginx.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  selector:
    app: {{ template "splunk.name" . }}-defaults
    release: {{ .Release.Name }}
  ports:
    - name: nginx-web
      port: {{ .Values.nginx.service.port }}
      targetPort: http
